# Generated by Django 5.2.8 on 2025-11-09 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión')], max_length=10)),
                ('name', models.CharField(max_length=48)),
                ('icon_name', models.CharField(default='label', max_length=32)),
                ('color_hex', models.CharField(default='#64748B', max_length=9)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pocket_type', 'order', 'name'],
                'unique_together': {('user', 'pocket_type', 'name')},
            },
        ),
    ]
