# Generated by Django 5.2.8 on 2025-11-09 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=8)),
                ('date', models.DateField()),
                ('payment', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], default='debito', max_length=10)),
                ('is_fixed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=280, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
