# Generated by Django 5.2.8 on 2025-11-10 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_moneytx_delete_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytx',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txs', to='finance.category'),
        ),
        migrations.AddField(
            model_name='moneytx',
            name='pocket_type',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión')], default='gasto', max_length=10),
        ),
        migrations.AddIndex(
            model_name='moneytx',
            index=models.Index(fields=['user', 'pocket_type', 'category_name'], name='finance_mon_user_id_ec1869_idx'),
        ),
        migrations.AddIndex(
            model_name='moneytx',
            index=models.Index(fields=['user', 'date'], name='finance_mon_user_id_eea0f2_idx'),
        ),
    ]
