# Generated by Django 5.2.9 on 2026-02-06 19:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_moneytx_category_moneytx_pocket_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3)),
                ('usd_cop_rate', models.DecimalField(decimal_places=4, default=Decimal('4000.0000'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
