# Generated by Django 5.2.9 on 2026-01-14 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=128, unique=True)),
                ('access_token', models.TextField()),
                ('institution_id', models.CharField(blank=True, default='', max_length=128)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=128)),
                ('mask', models.CharField(blank=True, default='', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, default='', max_length=64)),
                ('subtype', models.CharField(blank=True, default='', max_length=64)),
                ('verification_status', models.CharField(blank=True, default='', max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.plaiditem')),
            ],
        ),
        migrations.AddIndex(
            model_name='plaiditem',
            index=models.Index(fields=['user', 'item_id'], name='banking_pla_user_id_fcaf0a_idx'),
        ),
        migrations.AddIndex(
            model_name='plaidaccount',
            index=models.Index(fields=['item', 'account_id'], name='banking_pla_item_id_2c4191_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plaidaccount',
            unique_together={('item', 'account_id')},
        ),
    ]
