# Generated by Django 5.2.9 on 2026-01-17 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='tx_cursor',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.CreateModel(
            name='PlaidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=128, unique=True)),
                ('account_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('merchant_name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iso_currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('unofficial_currency_code', models.CharField(blank=True, default='', max_length=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=16)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.plaiditem')),
            ],
        ),
        migrations.CreateModel(
            name='BankAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Income')], default='income', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='banking.plaiditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_alerts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='banking.plaidtransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='plaidtransaction',
            index=models.Index(fields=['item', 'account_id'], name='banking_pla_item_id_da7466_idx'),
        ),
        migrations.AddIndex(
            model_name='plaidtransaction',
            index=models.Index(fields=['item', 'date'], name='banking_pla_item_id_9eac0c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankalert',
            index=models.Index(fields=['user', 'seen_at', 'created_at'], name='banking_ban_user_id_7d42b5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankalert',
            index=models.Index(fields=['item', 'created_at'], name='banking_ban_item_id_fb208b_idx'),
        ),
    ]
