# Generated by Django 5.2.9 on 2026-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_plaiditem_last_synced_at_plaiditem_tx_cursor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankalert',
            name='kind',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=32),
        ),
    ]
